"""
ComfyUI API Plugin
支持使用多种 AI API 进行图像和视频生成
- Nano Banana: Google Nano Banana 图像生成
- Gemini Banana: Google Gemini 3 Pro 图像生成
- Doubao Seedance: AI 视频生成
- Doubao Seedream: AI 图像生成
"""

# 导入 Doubao Seedance 节点（视频生成）
from .doubao_seedance_node import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_SEEDANCE, 
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_SEEDANCE
)

# 导入 Doubao Seedream 节点（图像生成）
from .doubao_seedream_node import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_SEEDREAM, 
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_SEEDREAM
)

# 导入 Nano Banana 图片生成节点
from .nano_banana_node import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_NANO_BANANA,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_NANO_BANANA
)

# 导入 Gemini Banana 图片生成节点
from .gemini_image_node import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_GEMINI_BANANA,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_GEMINI_BANANA
)

# 导入banana视频生成Pro节点
# from .video_generation_pro_node import (
#     NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_VIDEO_PRO,
#     NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_VIDEO_PRO
# )

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_SEEDANCE,
    **NODE_CLASS_MAPPINGS_SEEDREAM,
    **NODE_CLASS_MAPPINGS_NANO_BANANA,
    **NODE_CLASS_MAPPINGS_GEMINI_BANANA,
    # **NODE_CLASS_MAPPINGS_VIDEO_PRO
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_SEEDANCE,
    **NODE_DISPLAY_NAME_MAPPINGS_SEEDREAM,
    **NODE_DISPLAY_NAME_MAPPINGS_NANO_BANANA,
    **NODE_DISPLAY_NAME_MAPPINGS_GEMINI_BANANA,
    # **NODE_DISPLAY_NAME_MAPPINGS_VIDEO_PRO
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']